networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev
  server:
    build: 
      context: ./ClipCloudServer
    ports:
      - 8000:8000
    env_file:
      - ./ClipCloudServer/.env
    networks:
      - dev
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build: 
      context: ./ClipCloudClient
    networks:
      - dev
    depends_on:
      - server
  postgres:
    image: postgres:latest
    env_file:
      - ./ClipCloudServer/.env
    environment:
      POSTGRES_USER: ${DB_USER:-rodion}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-clipcloud}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./ClipCloudServer/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
