networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev
  server:
    build: 
      context: ./ClipCloudServer
    ports:
      - 8000:8000
    networks:
      - dev
    depends_on:
      - redis
  client:
    build: 
      context: ./ClipCloudClient
    networks:
      - dev
    depends_on:
      - server
  redis:
    image: redis:latest
    container_name: redis_container
    volumes:
      - ./redisdata:/data
    networks:
      - dev

